#!/usr/bin/python

import sys, os



if len(sys.argv) == 1:
    print "Usage: \"grab {filename} {string}\""
else:
    filename = sys.argv[1]
    text = sys.argv[2]
    
    with open (filename, 'rU') as f:
        for i, line in enumerate(f, start=1):
            if text.lower() in line.lower():
                print ("{}: {}".format(i, line.strip()))
            else:
                print "{} not found in {}".format(text, os.path.basename(filename))

