#!/usr/bin/python

import warnings
from Bio.Seq import Seq
from Bio import SeqIO, BiopythonWarning
from Bio.Alphabet.IUPAC import ExtendedIUPACDNA
import sys

"""
Supply a .fasta formatted sequence and a short sequence in the translated sequence to print the translated sequence in the correct reading frame
Results from GeneWiz can be translated quickly by cd into directory and | for i in ./*; do translater $i `4+ sequence`; done
Results can easily be pasted into Clustal Omega to compare sequences
"""

warnings.simplefilter('ignore', BiopythonWarning)

if len(sys.argv) < 3: print "Usage: translater \"/path/to/file\" \"Known sequence in protein\""; sys.exit()

with open(sys.argv[1], "r") as f:
    for fasta in SeqIO.parse(f, format="fasta"):
        sequence = Seq(str(fasta.seq), ExtendedIUPACDNA())
        reverse = Seq(str(sequence.reverse_complement()), ExtendedIUPACDNA())
        print ">" + fasta.id
        check = sys.argv[2].upper().strip()
        for x in range(0,3):
            forward = sequence[x:].translate()
            if check in forward: print forward
            backward = reverse[x:].translate()
            if check in backward: print backward

